name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.10
      options: --shm-size=2gb

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mytestdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user -d mytestdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://user:password@postgres:5432/mytestdb

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install uvicorn[standard]
          pip install playwright pytest-playwright
          playwright install chromium

      - name: Run unit tests
        run: pytest tests/unit/ -vv

      - name: Run integration tests
        run: pytest tests/integration/ -vv

      - name: Run E2E tests
        env:
          PLAYWRIGHT_BROWSERS_PATH: /ms-playwright
        run: pytest tests/e2e/ -vv --disable-warnings
